# Install docker
deploy_docker = ENV['ROUSSELTM_DEPLOY_DOCKER'] || false

# Deploy docker SWARM
deploy_swarm = ENV['ROUSSELTM_DEPLOY_SWARM'] || false

#Managers 
manager_ip = "192.168.3.2"

#Workers 
numworkers = 2
instances = []
(1..numworkers).each do |n| 
  instances.push({:name => "worker#{n}", :ip => "192.168.3.#{n+2}"})
end

#Cluster IP
File.open("./hosts", 'w') { |file| 
    file.write("#{manager_ip} manager manager.tp.elearning.rousseltm.fr\n")
    instances.each do |i|
        file.write("#{i[:ip]} #{i[:name]} #{i[:name]}.tp.elearning.rousseltm.fr\n")
    end
}

$script = <<-SCRIPT
cat /tmp/hosts >> /etc/hosts
sed -i 's/#DNS=/DNS=8.8.8.8/g' /etc/systemd/resolved.conf
systemctl restart systemd-resolved
SCRIPT


Vagrant.configure("2") do |config|
    
    #Création du Manager
    config.vm.define "manager" do |i|
        i.vm.box = "bento/ubuntu-24.04"
        i.vm.hostname = "manager"
        i.vm.network "private_network", ip: "#{manager_ip}"
        i.vm.network "forwarded_port", guest: 80, host: 80
        i.vm.network "forwarded_port", guest: 8080, host: 8080
        i.vm.network "forwarded_port", guest: 3000, host: 3000
        i.vm.network "forwarded_port", guest: 9090, host: 9090
        i.vm.synced_folder "D:\\git\\elearning\\web\\projects\\docker", "/opt/projects",
        #i.vm.synced_folder "projects", "/opt/projects",
            mount_options: ["dmode=775,fmode=777"]
        if File.file?("./hosts") 
          i.vm.provision "file", source: "hosts", destination: "/tmp/hosts"
          i.vm.provision "shell", inline: $script, privileged: true
        end
        if deploy_docker || deploy_swarm
            i.vm.provision "docker"
        end
        if deploy_swarm 
            i.vm.provision "shell", inline: "docker swarm init --listen-addr #{manager_ip} --advertise-addr #{manager_ip}"
            i.vm.provision "shell", inline: "docker swarm join-token -q worker > /vagrant/swarm-token-worker"
        end
    end 

    #Création des workers 
    instances.each do |instance| 
        config.vm.define instance[:name] do |i|
            i.vm.box = "bento/ubuntu-24.04"
            i.vm.hostname = instance[:name]
            i.vm.network "private_network", ip: "#{instance[:ip]}"
            i.vm.synced_folder "D:\\git\\elearning\\web\\projects\\docker", "/opt/projects",
            #i.vm.synced_folder "projects", "/opt/projects",
                mount_options: ["dmode=775,fmode=777"]
            if File.file?("./hosts") 
                i.vm.provision "file", source: "hosts", destination: "/tmp/hosts"
                i.vm.provision "shell", inline: $script, privileged: true
            end
            if deploy_docker || deploy_swarm
                i.vm.provision "docker"
            end
            if deploy_swarm
                i.vm.provision "shell", inline: "docker swarm join --advertise-addr #{instance[:ip]} --listen-addr #{instance[:ip]}:2377 --token `cat /vagrant/swarm-token-worker` #{manager_ip}:2377"
            end
        end 
    end

    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/Projet E-learning Docker by RousselTM"]
        v.memory = 1024
        v.cpus = 1
    end

end